targets:
  $default:
    sources:
      - integration_test/**   # By default, build runner will not generate code in the integration folder
      - test/**               # so we override paths for code generation here
      - lib/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: njw_bdd_steps # any named folder shares steps between widget and integration tests
          # testMethodName: customTestMethodName
          #testerType can be used for patrolTester
          # and tesername #
          # and testMEthodname patrolTest or PatrolWidgetTest etc.
          include: package:bdd_widget_test/bdd_options.yaml
        generate_for:
          - test/**
          - integration_test/**